---
sudo: false
cache: bundler
language: ruby
bundler_args: --without development
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-14.04"
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    script: bundle exec rake beaker
